version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: sil_postgres
    restart: always
    environment:
      POSTGRES_DB: sil_lab
      POSTGRES_USER: sil_user
      POSTGRES_PASSWORD: sil_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sil_network

  backend:
    build: ./server
    container_name: sil_backend
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://sil_user:sil_password@postgres:5432/sil_lab
    networks:
      - sil_network

  frontend:
    build: ./frontend
    container_name: sil_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - sil_network

  nginx:
    image: nginx:alpine
    container_name: sil_nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - sil_network

  # Optional: keep pgAdmin in prod if you want
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sil_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sil.lab
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - sil_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  sil_network:
    driver: bridge
