version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sil_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sil_lab
      POSTGRES_USER: sil_user
      POSTGRES_PASSWORD: sil_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sil_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sil_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sil.lab
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - sil_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  sil_network:
    driver: bridge
 